[package]
name = "ansipng"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lodepng = "3.4"
rgb = "0.8"

[[bin]]
name = "ansipng"
path = "main.rs"
